spring:
  kafka:
    bootstrap-servers: kafka:9092
    topic: document-uploaded
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";

  data:
    mongodb:
      uri: mongodb://localhost:27017/documents

server:
  port: 8081

minio:
  url: http://minio:9000
  access-key: admin
  secret-key: password
  bucket: documents